In [7]:
import numpy as np
x = np.array([[1,2], [3,4]], dtype=np.float64)
y = np.array([[5,6], [7,8]], dtype=np.float64)

print(x + y)
print(np.add(x, y))

# You got dot in result because of using float64 dtype, 6. => 6.0

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]


In [8]:
# Elementwise difference; both produce the array
print ( x - y )
print(np.subtract(x, y))

[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]


In [9]:
# Elementwise division
print (x / y)
print(np.divide(x, y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [10]:
print ( x * y)
print(np. multiply(x, y))

[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]


In [11]:
import numpy as np

x = np.array([[1,2], [3,4]])
y = np.array([[5,6], [7,8]])

v = np.array()

TypeError: array() missing required argument 'object' (pos 0)

In [ ]:
import numpy as np
x = np.array([[1,2], [3,4], [5,6]])

print(np.max(x))
print(np.min(x))
print(np.sum(x))

6
1
21


In [ ]:
w = np.array([[1], [2], [3]])
print(w)
w.shape

[[1]
 [2]
 [3]]


(3, 1)

In [ ]:
y = w.reshape(-1, ) # we can pass -1 as one dimension and numpy will infer the correct size based on our matrix
print(y)
y.shape

[1 2 3]


(3,)

#### Broadcasting two arrays together follows these rules
Rule 1: If two arrays differ in their number of dimensions, the shape of the one with fewer dimensions is padded with ones on its leading(left) side.
For example, below 'a' will be implicitly extended to shape(1, 3)

In [12]:

import numpy as np
a = np.array([1,2,3])
b = np.array([[4],[5],[6]])
print(a+b)

[[5 6 7]
 [6 7 8]
 [7 8 9]]


Rule-2: If the shape of the two arrays does not match in any dimension, the arry with shape equal to 1 in that dimension is stretched to match the other shape.
For example, in the following cell 'a' will be implicitly extended to shape (3,2)

In [ ]:
a = np.array([[1],[2],[3]]) # has shape (3,1)
print(a)
b= np.array([[4,5], [6,7], [8,9]]) # has shape (3,2)
print(b)

c = a+b
print(c)

[[1]
 [2]
 [3]]
[[4 5]
 [6 7]
 [8 9]]
[[ 5  6]
 [ 8  9]
 [11 12]]


Rule-3: If in any dimension the sizes disagree and neither is equal to 1, an error is raised

In [13]:

a = np.array([[1],[2],[3], [4]]) # shape (4,1)
b= np.array([[4,5], [6,7], [8,9]]) # shape (3,2)
c = a + b
print(c)

ValueError: operands could not be broadcast together with shapes (4,1) (3,2) 

In [14]:
# Solving linear equations

import numpy as np

# Coefficient matrix A
A = np.array([
    [3, 1, -2],
    [2, -1, 1],
    [1, 2, 3]
])

# Constants on the right-hand side
B = np.array([9, 3, 12])

# Solve the system
solution = np.linalg.solve(A, B)

# Output results
x, y, z = solution
print(f"x = {x}")
print(f"y = {y}")
print(f"z = {z}")


x = 2.6
y = 3.2
z = 1.0
