In [1]:
import numpy as np

# Python list
list_example = [1, 2,'Hello', 3.5, [5, 7, 8]]

# Numpy Array
# We force numpy to use dtype as int32
array_example = np.array([1,2,3,4,5], dtype=np.int32)

In [2]:
array_example

array([1, 2, 3, 4, 5], dtype=int32)

In [3]:
# using heterogineous data, numpy chooses dtype itself
array_example = np.array([1,2,'hello', 3])

In [4]:
array_example

array(['1', '2', 'hello', '3'], dtype='<U21')

In [5]:
a = np.array([1,2,3])

In [6]:
print(type(a), '\n', 'shape: ', a.shape, '\n', 'Indexed elements: ', a[0], a[1], a[2])
print(a)

<class 'numpy.ndarray'> 
 shape:  (3,) 
 Indexed elements:  1 2 3
[1 2 3]


In [7]:
b = np.array([[1,2], [3,4]])
print(b)

[[1 2]
 [3 4]]


In [8]:
print(b.shape)

(2, 2)


In [9]:
b.ndim

2

In [10]:
c = np.array([
    [[1,2], [3,4]], 
    [[1,3], [3,7]]
    ])
print(c)

[[[1 2]
  [3 4]]

 [[1 3]
  [3 7]]]


In [11]:
# Dimentions are also called Rank
c.ndim

3

In [12]:
print(c.shape)

(2, 2, 2)


In [13]:
np.__version__

'2.0.2'

In [14]:
# Create a rank 2 array of shape (3, 4)
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
# Use slicing to pull
b= a[0:2, 1:3]
print(b)
print(a.shape)

[[2 3]
 [6 7]]
(3, 4)


In [15]:
# Create a rank 2 array of shape (3, 4)
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [16]:
row_r1 = a[1, :]
row_r2 = a[1:2, :]
row_r3 = a[[1], :]
print(row_r1, row_r1.shape)
print(row_r2, row_r2.shape)
print(row_r3, row_r3.shape)

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[[5 6 7 8]] (1, 4)


In [17]:
a = np.zeros((2,2)) # Create an array of all zeros
print(a)

[[0. 0.]
 [0. 0.]]


In [18]:
b = np.ones((1,2)) # create an array of all ones
print(b)

[[1. 1.]]


In [19]:
c = np.full((2,2), 2) # Create a constant array
print(c)

[[2 2]
 [2 2]]


In [20]:
d = np.eye(2) # create a 2*2 identity matrix, identity matrix is always a square matrix
print(d)
print(d.dtype)  # dtype = int32 => Provide your dtype

[[1. 0.]
 [0. 1.]]
float64


In [21]:
e = np.random.random((2,2)) # Create an array filled with random values
print(e)

[[0.69915935 0.6323177 ]
 [0.47001418 0.42355442]]


### vstack() and hstack() (row_stack and column_stack)
Sometimes, we may want to construct an array from existing arrays by 'stacking' the existing arrays, either vertically or horizontally. We can use vstack() or row_stack and hstack() or column stack, respectively

In [22]:
a = np.array([1,2,3])
b = np.array([4,5,6])
np.vstack((a,b))

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
a = np.array([[7], [8], [9]])
print(a)
b = np.array([[4], [5], [6]])
print(b)
np.hstack((a,b))

[[7]
 [8]
 [9]]
[[4]
 [5]
 [6]]


array([[7, 4],
       [8, 5],
       [9, 6]])

In [24]:
# 2D Array Slicing (Matrix)

a = np.arange(12).reshape(3,4)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [25]:
a[1]

array([4, 5, 6, 7])

In [26]:
a[1,2]

np.int64(6)

In [27]:
a[:, 1]

array([1, 5, 9])

In [28]:
a[::2, 1::2]

array([[ 1,  3],
       [ 9, 11]])

In [29]:
b = a[::2,] # We get the below (2,4) array
print(b)

[[ 0  1  2  3]
 [ 8  9 10 11]]


In [30]:
a[:, 1::2] #Now we extract colums from all the rows in b

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11]])

In [34]:
a = 5
a = 6
print(a)
b = 6
print(b)
c = 'hii'
d = 5689
d[0] = 5
c[0] = 't'
print(c)

6
6


TypeError: 'int' object does not support item assignment

In [1]:
a = [1,2,3,4]
a[2] = 9
print(a)
b = map(str, a)
b =''.join(b)
print(b)

[1, 2, 9, 4]
1294
