In [2]:
import numpy as np

a  = np.zeros((3,3), dtype = np.int64)
a[:] = 2 # select all rows and assign 3 to it
## a.fill(8) # fills every element with the value specified (in place)
## a += 3 # assignment operator adds 3 to all the elements in the 2D matrix
! a /= 3 # gives error, as the result will be in float but our dtype is int
print('Array A\n',a) 
print(a.dtype)

zsh:1: command not found: a
Array A
 [[2 2 2]
 [2 2 2]
 [2 2 2]]
int64


In [3]:
b = np.arange(1, 10).reshape((3,3))
print(b)
print(b.dtype)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
int64


In [4]:
array_sum = a.sum()
array_sum = a.sum(0) # axis of 0, sums each of our columns
array_sum = b.sum(axis = 1) # axis of 1, sum each of our rows
print(array_sum) 

[ 6 15 24]


In [5]:
array_product = b.prod() # multiplies all the elements
array_average = b.mean()
array_max, array_min = b.max(), b.min()
print(array_max, array_min)
print(array_average)
print(array_product)

9 1
5.0
362880


In [6]:
# gives the index where max and min values are located
array_max_index, array_min_index = b.argmax(), b.argmin()
print(array_max_index, array_min_index)

8 0


In [7]:
# peak_to_peak = b.ptp()
peak_to_peak = b.max() - b.min()
print(peak_to_peak)

8


In [8]:
# flatten arrays
array_flat = b.reshape(b.size)
array_flat = b.flatten() # makes a copy
array_flat = b.ravel() # similar result but makes a view, mutates the original array
print(array_flat)

[1 2 3 4 5 6 7 8 9]


In [9]:
# repeat values/arrays
array_repeat = np.repeat(255, 3) # 1st arg = value, 2nd arg = no. of reps
array_repeat = np.repeat(b, 3) # we get flattened vertion of b with all its values repeated 3 times
array_repeat = np.repeat(b, 3, axis = 1) # repeat row items three times
array_repeat_cols = np.repeat(b, 3, axis=0) # for columns
array_unique = np.unique(array_repeat, axis = 0) # gives unique elements, cancels the repeated elements
print(array_repeat)
print(array_repeat_cols)

[[1 1 1 2 2 2 3 3 3]
 [4 4 4 5 5 5 6 6 6]
 [7 7 7 8 8 8 9 9 9]]
[[1 2 3]
 [1 2 3]
 [1 2 3]
 [4 5 6]
 [4 5 6]
 [4 5 6]
 [7 8 9]
 [7 8 9]
 [7 8 9]]


In [10]:
array_diagonal = np.diagonal(b) # gives all the diagonal elements
array_diagonal = np.diagonal(b, offset=-1) # gives one diagonal below the main one
print(array_diagonal)

[4 8]


In [11]:
# conversion and storage
my_list = b.tolist()
print('b is', type(b))
print('mylist is', type(my_list))

b is <class 'numpy.ndarray'>
mylist is <class 'list'>


In [12]:
# convert np arry to file
b.tofile('my_array.txt', sep=',') # sep => separater here is comma

In [15]:
# transposition
array_swapped = np.swapaxes(b, 0, 1) # flip axix 0 with axis 1
array_swapped = b.transpose(1, 0) # flip axis 1 with axis 0
array_swapped = b.T # attribute method
print(array_swapped)

[[1 4 7]
 [2 5 8]
 [3 6 9]]
