In [2]:
import numpy as np

a = np.array([1, 2, 3, 4])        # Shape: (4,) → 1D vector
b = a.reshape(1, 4)               # Shape: (1, 4) → Row vector (2D)
c = a.reshape(4, 1)               # Shape: (4, 1) → Column vector (2D)

print(a)
print("a.shape =", a.shape)      # (4,)
print(b)
print("b.shape =", b.shape)      # (1, 4)
print(c)
print("c.shape =", c.shape)      # (4, 1)


[1 2 3 4]
a.shape = (4,)
[[1 2 3 4]]
b.shape = (1, 4)
[[1]
 [2]
 [3]
 [4]]
c.shape = (4, 1)


In [ ]:
# Dot product: 1D vector ⋅ 1D vector
np.dot(a, a)        # OR: a @ a
# 1*1 + 2*2 + 3*3 + 4*4 = 30
# Result: scalar (number)


np.int64(30)

In [ ]:
# Row vector (1, 4) ⋅ Column vector (4, 1)
np.dot(b, c)
'''
Shape: (1, 4) ⋅ (4, 1) → (1, 1)
→ [[30]] (a scalar inside a matrix)

Matrix multiplication: 1*4 * 4*1 = 1*1
'''

'\nShape: (1, 4) ⋅ (4, 1) → (1, 1)\n→ [[30]] (a scalar inside a matrix)\n\nMatrix multiplication: 1*4 * 4*1 = 1×1\n'

In [ ]:
# Column vector (4, 1) ⋅ Row vector (1, 4)
np.dot(c, b)
'''
Shape: (4, 1) ⋅ (1, 4) → (4, 4)

This creates a matrix: This is called an outer product.
Matrix multiplication: 4*1 * 1*4 = 4*4
'''

array([[ 1,  2,  3,  4],
       [ 2,  4,  6,  8],
       [ 3,  6,  9, 12],
       [ 4,  8, 12, 16]])

In [ ]:
np.dot(b, b)
# Error: shapes (1,4) and (1,4) not aligned
'''
You can't multiply (1*4) * (1*4).
You’d have to transpose one of them.
'''


NameError: name 'np' is not defined

✅ Shape Summary Table
Operation	Shapes	        Result	        Meaning
a @ a	(4,) × (4,)	        Scalar	        Standard dot product
b @ c	(1, 4) × (4, 1)	    (1, 1)	        Dot product as 2D
c @ b	(4, 1) × (1, 4)	    (4, 4)	        Outer product
b @ b	(1, 4) × (1, 4)	    ❌ Error	        Misaligned shapes
b @ b.T	(1, 4) × (4, 1)	    (1, 1)	        ✅ Transposed works